### ISSUE TITLE
The brainvisa executable always tries to use the default system Python

### ISSUE THREAD

**Issue by ylep** [brainvisa/axon#20]
The `brainvisa` shell script will always try to launch BrainVISA using `python`, which is the default system version. Therefore, on Ubuntu 16.04 it will try to launch it using Python 2, even if BrainVISA has been compiled with Python 3.

I think we should take 2 actions here:

- generate the `brainvisa` script from a new file, `brainvisa.in`, using CMake, hardcoding the Python version from `PYTHON_EXECUTABLE` at the beginning of `pythonexelist`

- add a safeguard to the startup code, so that in case of a version mismatch it fails with a useful error message

**Comment by denisri** [comment]
Up to now we used to work around this problem by making a symlink in the build three, bin/python points to /usr/bin/python or /usr/bin/python3 depending on the configuration of the build three. However this operation is manual, nothing does it for you and the trick is totally undocummented.
* Generating a script would be possible for the "brainvisa" command, but we have many python commands and scripts here, and the sources of axon (as many other projects) are otherwise agnostic to python version. Many projects would have the same issue.
* The safeguard option would only be possible when we can know which is the expected python version. Axon sources don't (unless we write it somewhere during configuration, but axon per se doesn't need to force a specific python version). We can guess when importing optional modules which really depend on a python version (such as soma.aims since it is a compiled module), but it is only an optional module in axon.
* So I come back to my 1st proposition: brainvisa-cmake could make a symlink to python3 in bin/ (on Unix systems) during the configuration step. Would it be OK ?

**Comment by ylep** [comment]
- I agree that the symlink is a good pragmatic solution.

- We can implement a safeguard by catching the exception that is raised upon importing `aimssip`. Maybe this could be located in [`aims/__init__.py`,](https://github.com/brainvisa/aims-free/blob/master/pyaims/python/soma/aims/__init__.py) so that doing `import soma.aims` outside of BrainVISA would still display an explicit error message.

- Considering that BrainVISA is heavily dependent on AIMS even for the core functionality (i.e. the builtin lists of file formats depend on AIMS) I think that we should at least display a very prominent warning message, maybe even make AIMS a strong dependency of axon and exit with an error if it cannot be imported.

I can take care of implementing these solutions, although probably not until early January :-)

**Comment by denisri** [comment]
The safeguard in aims import would be a good idea...
At brainvisa startup, aims should not be mandatory. If it is, this is a mistake. However yes aims is loaded at some point (in a try..except normally), and we can consider printing the appropriate message in such a case. But perhaps printing the message in aims.__init__ would be enough: it would work also for brainvisa.

**Comment by ylep** [comment]
With the new safeguard in AIMS (https://github.com/brainvisa/aims-free/commit/2ca2809d5bb9414f12ade8238421c13b45729a72) and change of error display in Axon (https://github.com/brainvisa/axon/commit/6f5c112e499961d2550a7b6edcb0a17a468e7744) the situation is now a bit better: when it is running under Python 2 and AIMS was compiled for Python 3, BrainVISA can now start up in a reasonable time, and all the processes that depend on AIMS appear greyed out. The actual 'version mismatch' exceptions are displayed when the user tries to open these processes, and they are also logged to the BrainVISA error log.

I will now try to display a prominent modal pop-up during BrainVISA start-up when the 'version mismatch' error is raised by AIMS.

**Comment by ylep** [comment]
The 3 steps that were discussed earlier are now implemented:
- `python` symbolic link in the build tree,
- clearer ImportError message when a compiled Python module fails to be imported due to a version mismatch,
- a pop-up appearing early during BrainVISA startup offering to abort in case of Python version mismatch.
