### ISSUE TITLE
Migrate away from __getinitargs__

### ISSUE THREAD

**Issue by ylep** [brainvisa/axon#22]
Many classes in soma-base and axon use `__getinitargs__`, which is an obsolete method that was used for pickling old-style classes (which were removed in Python 3), or its companion method `__getinitkwargs__`. Therefore, these objects cannot be pickled under Python 3.

The future-proof alternative is to make classes into new-style classes, and use `__getnewargs__` and `__getnewargs_ex__`. These methods are now also recognized by the Minf serializers (since https://github.com/populse/soma-base/commit/23dd0bace8b1c1f537141ec41b0dac0c80422f16).

See also the corresponding issue for soma-base: https://github.com/populse/soma-base/issues/4

**Comment by sapetnioc** [comment]
After a quick look at  the classes with `__getinitargs__`, the need for this method is not obvious in most cases. Its interest may had been to manage attributes that were translated. In that case untranslated values were returned by `__getstate__` and forcing a call to `__init__` during unpickling would start a new translation. I do not know if I miss something but if it is just that, we can forget this feature since we do not maintain translation anymore.

Anyway, I believe that in Python 3, there is no direct way to call `__init__` when unpickling. To change the default behavior for restoring the object state, one must implement `__setstate__`. If we want to keep the behavior of `__getinitargs__`, I believe we should implement a `__setstate__` that would call `__init__`. But, should'nt we just get rid of `__getinitargs__` ?

**Comment by sapetnioc** [comment]
Many `__getinitargs__` are used by the minf writer to store the content of objects (for instance in BrainVISA log). Therefore we may rename these methods (because they are not special methods anymore in Python 3) but in many cases we cannot remove them completly. I am not sure renaming is worth the effort.

**Comment by ylep** [comment]
> we may rename these methods (because they are not special methods anymore in Python 3) but in many cases we cannot remove them completly. I am not sure renaming is worth the effort.

Couldn’t we just rename these methods to `__getnewargs__`? These are also supported by the Minf serializers:

https://github.com/populse/soma-base/blob/b6449cd1b765cadf5b7415c16177a1f6266269ed/python/soma/minf/tree.py#L196-L206

There may be bad side-effects of doing that, I haven’t looked at it close enough to be sure.

**Comment by sapetnioc** [comment]
I would not try this renaming for the next releases (that was my first idea).

**Comment by denisri** [comment]
If we're not sure of the side effects, maybe we'd better do that after the 5.1 release ?

**Comment by ylep** [comment]
I agree, let's do it on `master`
