### ISSUE TITLE
The brainvisa-share database is not pre-indexed when installed

### ISSUE THREAD

**Issue by ylep** [brainvisa/axon#44]
When compiling `axon` in a fresh casa-distro environment, the `brainvisa-shared` database is not indexed (“updated”), so its objects cannot be looked up. This makes that database unusable in user images, and also makes some tests fail, e.g. [for DISCO](https://new.brainvisa.info/builds/job/disco-minimal-ubuntu-18.04/10/):

```
RuntimeError: Mandatory argument <em>label_translation</em> of view_sulci_to_be_studied_1 has no value
```

**Comment by denisri** [comment]
Yes I think I have already seen that. It used to be done, but apparently it's not any more. I don't remember where this was done...

**Comment by denisri** [comment]
When should it be done ?
- at each build ? This is a bit long for an unconditional step since it needs to start brainvisa and load all toolboxes
- within the install procedure ? Maybe this doesn't answer your question ?
Moreover which databases should be updated ? Only the "main" brainvisa-share database ? (Constellation, for instance, includes other atlas databases)

**Comment by sapetnioc** [comment]
I think this update should be part of the testing procedure. This would fix the testing problems for both dev and user environments. But I guess it should also be done for users. Either when creating user images or after the setup (or both).

**Comment by ylep** [comment]
- I agree with @sapetnioc the update should be part of tests, this is actually what I had before in DISCO

- On the other hand, the update procedure cannot be performed on a user image because the filesystem is read-only. There we need it to happen during the install, I guess.

**Comment by denisri** [comment]
I think I remember a few things now: in the modular installer, each toolbox could install its own data (and hierarchy parts) in the shared database, thus its indexation could not be done upstream: this had to be done after each installation of new toolboxes by the user, in the installer post-install scripts: the database file itself was not part of the package files, it was created afterwards. Maybe this was not done completely well also, however it was not done earlier and that was "normal".
Now that modularity is gone, and especially now that the package files are read-only in a read-only image, we can and should build the indexation at "install" (packaging, actually) time, so that the database file is included in the image. But the install procedure is thus not the same as it used to be.

**Comment by ylep** [comment]
This works now, thanks! However, there is still one annoying bit: the brainvisa-share database is shown as out-of-date by BrainVISA:

    Database /casa/install/share/brainvisa-share-5.0 must be updated because the database file is too old.

Here is the code in *axon* that triggers this warning:

https://github.com/brainvisa/axon/blob/29ce5c1c93a9b84e72d2cd1546054d237bf074f0/python/brainvisa/data/sqlFSODatabase.py#L699-L702

Is there a way that we could make the *mtime* of the sqlite database later than the fso during installation?

**Comment by denisri** [comment]
Well you're right there is still a problem: once the sqlite file exists, it is never updated by the build system because we don't have correct dependencies on all files in the brainvisa-share project, and on the ontology files from each toolbox. It's difficult to address in cmake. We could call `brainvisa -b --setup` unconditionally but it takes a significant time.
I don't know if it's the same problem as the one you mention: I have not checked when the `fso` files are created / updated, it it's the same `brainvisa -b --setup` which creates them in a different order from the one they are checked later, or if the `fso` files are updated at a later moment without the `sqlite` files being rebuilt.

**Comment by ylep** [comment]
If it can make things easier, I am in favor of calling `brainvisa -b --setup` unconditionally during `install-runtime`. Installation is not a command that is run very often, I think that we can easily tolerate the overhead.

If we have to run `brainvisa -b --setup` at build time, then it would be different story.

**Comment by denisri** [comment]
Can you try that again ?

**Comment by ylep** [comment]
The warning still showed up [in the nightly build](https://new.brainvisa.info/builds/job/disco-minimal-nightly/19/):

    Database /casa/install/share/brainvisa-share-5.0 must be updated because the database file is too old.

**Comment by denisri** [comment]
Maybe I understand: when installing, files are copied in a non-defined order, thus the sqlite file may be copied before the python files defining the ontology, and is thus considered outdated. We have to find a way to "touch" it after install is finished.
(by the way my last commit is pointless)

**Comment by denisri** [comment]
I have tried something else... tell me if it works or not.

**Comment by ylep** [comment]
Doesn't seem to turn out that well

```
======================================================================
ERROR: test_find_paths (__main__.TestTransformationManager)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/casa/host/build/python/brainvisa/tests/test_registration.py", line 81, in setUp
    self.database = self.create_test_database()
  File "/casa/host/build/python/brainvisa/tests/test_registration.py", line 66, in create_test_database
    database_directory, 'brainvisa-3.2.0', context=defaultContext(), settings=self.database_settings)
  File "/casa/host/build/python/brainvisa/data/sqlFSODatabase.py", line 718, in __init__
    if self.createTables():
  File "/casa/host/build/python/brainvisa/data/sqlFSODatabase.py", line 1089, in createTables
    if create and os.path.exists(self.sqlDatabaseFile):
UnboundLocalError: local variable 'create' referenced before assignment
```

Full log at https://new.brainvisa.info/builds/job/brainvisa-master-ubuntu-18.04/99/

**Comment by denisri** [comment]
OK, I have pushed a fix.

**Comment by denisri** [comment]
Still not fixed. There is no (visible) error anymore but after install the database is still outdated.

**Comment by denisri** [comment]
I will call it manually from casa_distro_admin create_user_image because I can't make it work using cmake.

**Comment by denisri** [comment]
It doesn't help either. But I have just noticed that from `/casa/host/install/brainvisa` in the dev image I don't get the outdated database message, whereas I have it in the user image (from `/casa/install/brainvisa`). Moreover in the user image the database file doesn't have the same date as in the dev image, so I suspect dates change during the copy into the final singularity image. Not sure how to check or fix it...

**Comment by denisri** [comment]
Finally fixed by the "touch".

**Comment by denisri** [comment]
This issue is not really fixed: some data are not included in the database. SPAM sulci models are not registered in the database, thus Morphologist asks to install them (and fails in a read-only image).
Things are definitely not done in the right order during install.

**Comment by denisri** [comment]
I spent a day trying to make cmake do the update at the right moment at the end of the "make install-runtime". I couldn't do it. I had to create another target "post-install".
And still, things are not updated correctly... Part of the SPAM models are still not in the database.

**Comment by denisri** [comment]
I think it's finally fixed.
